import { type NextPage } from "next";
import { SignIn, useUser, SignInButton, SignOutButton } from "@clerk/nextjs";
import {} from "@clerk/nextjs";
import Head from "next/head";
import Link from "next/link";
import dayjs from "dayjs";
import relativeTime from "dayjs/plugin/relativeTime";
import { LoadingPage, Spinner } from "../components/loader";

dayjs.extend(relativeTime);

import { RouterOutputs, api } from "~/utils/api";
import Image from "next/image";
import { useState } from "react";
import { type } from "../utils/api";
import { toast } from "react-hot-toast";

type UserPost = RouterOutputs["posts"]["getAll"][number];

const PostView = (props: UserPost) => {
  const { post, author } = props;
  return (
    <div className=" flex items-center" key={post?.id}>
      <Image
        className="h-10 w-10 rounded"
        src={author.profileImageUrl}
        alt=""
        width={46}
        height={46}
      />

      <div>
        <div className=" flex gap-1 text-sm text-slate-400">
          <Link href={`/@${author.username}`}>
            <div>@{author.username}</div>
          </Link>
          <div>·</div>
          <Link href={`/post/${post.id}`}>
            <div className=" capitalize">{dayjs(post.createdAt).fromNow()}</div>
          </Link>
        </div>
        <div>{post?.content}</div>
      </div>
    </div>
  );
};

const Feed = () => {
  const { data, isLoading: postLoading } = api.posts.getAll.useQuery();
  if (postLoading) return <LoadingPage />;
  if (!data) return <div>no data</div>;

  return (
    <div>
      {data?.map((fullPost) => (
        <PostView {...fullPost} key={fullPost.post.id} />
      ))}
    </div>
  );
};

const CreatePostWizard = () => {
  const { user } = useUser();
  const ctx = api.useContext();
  const { mutate: triggerPost, isLoading: isPosting } =
    api.posts.create.useMutation({
      onSuccess: async () => {
        setContent("");
        await ctx.posts.getAll.invalidate();
      },
      onError: (err) => {
        toast.error(err.message);
      },
    });
  const [content, setContent] = useState<string>("");
  const createPost = (e: React.KeyboardEvent<HTMLInputElement>) => {
    if (e.key === "Enter") {
      e.preventDefault();
      triggerPost({ content });
    }
  };

  if (!user) return null;
  return (
    <div className="relative flex gap-4">
      <Image
        className=" rounded"
        src={user.profileImageUrl}
        alt=""
        width={46}
        height={46}
      />
      <input
        type="text"
        className="flex-grow   bg-transparent outline-none"
        placeholder="Search"
        value={content}
        onChange={(e) => setContent(e.target.value)}
        onKeyDown={createPost}
        disabled={isPosting}
      />
      {isPosting && <Spinner />}
    </div>
  );
};

const Home: NextPage = () => {
  const { isLoaded: userLoaded, isSignedIn } = useUser();
  api.posts.getAll.useQuery();
  if (!userLoaded) return <div />;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <div className=" mx-auto md:max-w-2xl">
          <div className=" border p-4">
            {!isSignedIn && <SignInButton />}
            {!!isSignedIn && <CreatePostWizard />}
            <SignIn path="/sign-in" routing="path" signUpUrl="/sign-up" />
          </div>
          <Feed />
        </div>
      </main>
    </>
  );
};

export default Home;
